window:
  startup_mode: Windowed

scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  normal:
    family: SF Mono Square
    style: Regular
  bold:
    family: SF Mono Square
    style: Bold
  size: 16.0
  use_thin_strokes: true

# Colors (Iceberg)
colors:
  primary:
    background: '#161821'
    foreground: '#d2d4de'
  normal:
    black:   '#161821'
    red:     '#e27878'
    green:   '#b4be82'
    yellow:  '#e2a478'
    blue:    '#84a0c6'
    magenta: '#a093c7'
    cyan:    '#89b8c2'
    white:   '#c6c8d1'
  bright:
    black:   '#6b7089'
    red:     '#e98989'
    green:   '#c0ca8e'
    yellow:  '#e9b189'
    blue:    '#91acd1'
    magenta: '#ada0d3'
    cyan:    '#95c4ce'
    white:   '#d2d4de'
