Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 30

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Style/FrozenStringLiteralComment:
  Enabled: false
