Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
