Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
