#!/bin/bash

d=$(cd $(dirname $0);pwd)
workdir='/tmp'

epel_url='http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm'
epel_basename=$(basename $epel_url)
epel_path="$workdir/$epel_basename"
wget $epel_url -P $workdir
rpm -ivh $epel_path
rm $epel_path

yum -y install vim bash-completion git subversion readline readline-devel zlib zlib-devel openssl openssl-devel libyaml libyaml-devel
yum -y groupinstall "Development Tools"

bash ${d}/link
bash ${d}/vim

echo Done!
