#!/bin/bash

d=$(cd $(dirname $0);pwd)/..

if [ ! -d $d/.vim/bundle ]; then
    mkdir -p $d/.vim/bundle
fi

if [ ! -d $d/.vim/bundle/neobundle.vim ]; then
    git clone git://github.com/Shougo/neobundle.vim $d/.vim/bundle/neobundle.vim
fi
